package: abort if tests fail

diff --git a/linux/package.sh.in b/linux/package.sh.in
--- a/linux/package.sh.in
+++ b/linux/package.sh.in
@@ -30,6 +30,18 @@ if ! ( sha1sum --check $check_sha1 ) then
 fi
 cd ..
 
+cp ncbi-blast-$BLASTVER+/bin/makeblastdb \
+    ${PROJECT_BINARY_DIR}/src/test/
+cp ncbi-blast-$BLASTVER+/bin/blastn \
+    ${PROJECT_BINARY_DIR}/src/test/
+prevpath=`pwd`
+cd ${PROJECT_BINARY_DIR}
+if ! ( make test ) then
+    echo 'make test failed! Aborted'
+    exit
+fi
+cd $prevpath
+
 cp ${PROJECT_SOURCE_DIR}/README.md npge-${VERSION}/README.txt
 
 cp \
diff --git a/windows/package.sh.in b/windows/package.sh.in
--- a/windows/package.sh.in
+++ b/windows/package.sh.in
@@ -20,6 +20,21 @@ if ! ( sha1sum --check $check_sha1 ) then
 fi
 cd ..
 
+cp ncbi-blast-$BLASTVER+/bin/makeblastdb.exe \
+    ${PROJECT_BINARY_DIR}/src/test/
+cp ncbi-blast-$BLASTVER+/bin/blastn.exe \
+    ${PROJECT_BINARY_DIR}/src/test/
+chmod +x ${PROJECT_BINARY_DIR}/src/test/*.exe
+cp npge-${VERSION}/vcomp100.dll \
+    ${PROJECT_BINARY_DIR}/src/test/
+prevpath=`pwd`
+cd ${PROJECT_BINARY_DIR}
+if ! ( make test ) then
+    echo 'make test failed! Aborted'
+    exit
+fi
+cd $prevpath
+
 awk 'sub("$", "\r")' ${PROJECT_SOURCE_DIR}/README.md > \
     npge-${VERSION}/README.txt
 
